"""Compatibility façade for authoritative projection implementations."""

from asago_scenario_generator.pipeline.projection_allocation import (  # noqa: F401
    _assemble_pattern_state,
    _check_simple_missing_slot,
    _direct_ingress_options,
    _gather_slot_options,
    _has_direct_ingress_activation,
    _has_source_influence_activation,
    _ingress_slot_index,
    _no_activation_violation,
    _project_authoritative_pattern,
    _record_missing_slot_issues,
    _relation_slot_ids,
    _resolve_ingress_activation,
    _slot_by_id,
    _source_influence_failure_issue,
    _source_influence_relation_links,
    _source_influence_relation_state,
    _source_influence_target_id,
    _target_ingress_reference,
    _zero_bindings_issue,
)
from asago_scenario_generator.pipeline.projection_allocator import (  # noqa: F401
    _AuthoritativeCandidateAllocator,
)
from asago_scenario_generator.pipeline.projection_qualification import (  # noqa: F401
    _authoritative_records_type_check,
    _catalog_content_pin,
    compute_authoritative_catalog_pin,
    _dedupe_projection_issues,
    _false_precondition_issue,
    _inapplicable_projection_issue,
    _incompatible_profile_issue,
    _infeasibility_key,
    _limitation_key,
    _profile_compatibility_gaps,
    _profile_and_condition_gate,
    _profile_gate_failure_issue,
    _precondition_results_or_none,
    _projection_is_applicable,
    _qualify_authoritative_pattern,
    _qualify_authoritative_records,
    _qualified_condition_state as _qualified_condition_state_from_qualification,
    _resolve_projection_budget,
    _resolve_qualified_patterns,
    _results_contain_false,
    _results_contain_unknown,
    _select_conditionally_required_steps,
    _sorted_emitted_candidates,
    _sorted_infeasibilities,
    _sorted_limitations,
    _unresolved_condition_issue,
    _unresolved_precondition_issue,
    _omitted_conditional_steps,
)

_qualified_condition_state = _qualified_condition_state_from_qualification
