"""STPA boundary schemas — Pydantic models for inter-SP data contracts.

Public API: import boundary schema classes from here rather than from
individual sub-modules.  Internal helpers (``_validation``) are not
re-exported.
"""

from asago_scenario_generator.stpa.models.control_structure import (
    ControlAction,
    ControlActionEffectKind,
    ControlActionTemporality,
    ControlStructure,
    ControlledProcess,
    CoordinationLink,
    CoordinationMechanism,
    ElementRef,
    FeedbackChannel,
    HeuristicResult,
    ProcessModelPart,
    ReferenceType,
    Responsibility,
    ResponsibilityConstraint,
    check_structural_heuristics,
    normalize_control_action_effect_kind,
)
from asago_scenario_generator.stpa.models.enriched_threat_set import (
    CatalogMapping,
    CoverageAnalysis,
    EnrichedThreatSet,
    StructuralThreat,
)
from asago_scenario_generator.stpa.models.causal_factor import (
    CausalEvidenceStatus,
    CausalFactor,
    CausalFactorKind,
    namespace_for,
    validate_factor_sources,
)
from asago_scenario_generator.stpa.models.run_identity import ExecutionRunIdentity
from asago_scenario_generator.stpa.models.omission_evidence import (
    ObservationOmissionEvidence,
    OmissionApplicability,
    OmissionDelivery,
    OmissionEvidenceEntry,
    OmissionSourceAttestation,
    SOURCE_ATTESTATION_FRAME,
    StateFactOmissionEvidence,
    StimulusOmissionEvidence,
    TRIGGER_DIGEST_FRAME,
)
from asago_scenario_generator.stpa.models.execution_classification import (
    AttackerInfluence,
    ExecutionActionKind,
    ExecutionResourceKind,
    ExecutionSurface,
    ExecutionTargetProfile,
    DiscoveryMode,
    DiscoveryProvenance,
    InventoryAuthority,
    InventoryCompleteness,
    InterpreterVerifierAgreement,
    McpInventoryObservation,
    McpToolObservation,
    ProfileBasis,
    SemanticAuthority,
    SourceProtocol,
    SimulationBehavior,
    TargetDiscoveryDiagnostic,
    TargetDiscoveryDiagnosticCode,
    TargetDiscoverySeverity,
    TargetInterpretationDisposition,
    TargetOperationEffect,
    TargetProfileOperation,
    TargetProfileResource,
    TargetSemanticInterpretation,
    TargetStateEffect,
    mcp_inventory_evidence_refs,
    mcp_resource_id,
    EXECUTION_TARGET_PROFILE_SCHEMA_VERSION,
)
from asago_scenario_generator.stpa.models.ica_enumeration import (
    ICA,
    ICAEnumeration,
    ICASlot,
    UCAType,
    candidate_id_for,
)
from asago_scenario_generator.stpa.models.loss_analysis import (
    Hazard,
    Loss,
    LossAnalysis,
    LossProvenance,
    SecurityConstraint,
)
from asago_scenario_generator.stpa.models.scenario_envelope import (
    ConsumerHints,
    GherkinSpec,
    ScenarioEnvelope,
    SystemContext,
)
from asago_scenario_generator.stpa.models.scenario_context import (
    ReachableCapability,
    ScenarioCatalogContext,
    ScenarioConstraint,
    ScenarioCoordinationPath,
    ScenarioControlPath,
    ScenarioGenerationContext,
    ScenarioHazard,
    ScenarioICAContext,
    ScenarioIdentity,
    ScenarioLoss,
    ScenarioObligationConsideration,
    ScenarioSourcePin,
    validate_factor_evidence,
)
from asago_scenario_generator.stpa.models.scenario_spec import (
    AttackerBDI,
    DefenderBDI,
    DefenderBelief,
    DefenderDesire,
    DefenderIntention,
    ScenarioSpec,
    ThreatSource,
)
from asago_scenario_generator.stpa.models.semantic_conditions import (
    AbsenceCondition,
    ActionPresenceCondition,
    ActionValueCondition,
    ClosedSemanticModel,
    DelayCondition,
    DurationCondition,
    OrderingCondition,
    SemanticBindingPlaceholder,
    SemanticBindingValueType,
    SemanticCondition,
    SemanticValue,
    StateValueCondition,
    WindowCondition,
    contains_binding_placeholder,
)

__all__ = [
    # loss_analysis
    "Hazard",
    "Loss",
    "LossAnalysis",
    "LossProvenance",
    "SecurityConstraint",
    # control_structure
    "ControlAction",
    "ControlActionEffectKind",
    "ControlActionTemporality",
    "ControlStructure",
    "ControlledProcess",
    "CoordinationLink",
    "CoordinationMechanism",
    "ElementRef",
    "FeedbackChannel",
    "HeuristicResult",
    "ProcessModelPart",
    "ReferenceType",
    "Responsibility",
    "ResponsibilityConstraint",
    "check_structural_heuristics",
    "normalize_control_action_effect_kind",
    # ica_enumeration
    "ICA",
    "ICAEnumeration",
    "ICASlot",
    "UCAType",
    "candidate_id_for",
    # enriched_threat_set
    "CatalogMapping",
    "CoverageAnalysis",
    "EnrichedThreatSet",
    "StructuralThreat",
    # scenario_context
    "ReachableCapability",
    "ScenarioCatalogContext",
    "ScenarioConstraint",
    "ScenarioCoordinationPath",
    "ScenarioControlPath",
    "ScenarioGenerationContext",
    "ScenarioHazard",
    "ScenarioICAContext",
    "ScenarioIdentity",
    "ScenarioLoss",
    "ScenarioObligationConsideration",
    "ScenarioSourcePin",
    # causal_factor
    "CausalEvidenceStatus",
    "CausalFactor",
    "CausalFactorKind",
    "namespace_for",
    "validate_factor_evidence",
    "validate_factor_sources",
    # run_identity
    "ExecutionRunIdentity",
    # omission_evidence
    "SOURCE_ATTESTATION_FRAME",
    "TRIGGER_DIGEST_FRAME",
    "ObservationOmissionEvidence",
    "OmissionApplicability",
    "OmissionDelivery",
    "OmissionEvidenceEntry",
    "OmissionSourceAttestation",
    "StateFactOmissionEvidence",
    "StimulusOmissionEvidence",
    # execution classification
    "AttackerInfluence",
    "ExecutionActionKind",
    "ExecutionResourceKind",
    "ExecutionSurface",
    "ExecutionTargetProfile",
    "DiscoveryMode",
    "DiscoveryProvenance",
    "InventoryAuthority",
    "InventoryCompleteness",
    "InterpreterVerifierAgreement",
    "McpInventoryObservation",
    "McpToolObservation",
    "ProfileBasis",
    "SemanticAuthority",
    "SourceProtocol",
    "SimulationBehavior",
    "TargetDiscoveryDiagnostic",
    "TargetDiscoveryDiagnosticCode",
    "TargetDiscoverySeverity",
    "TargetInterpretationDisposition",
    "TargetOperationEffect",
    "TargetProfileOperation",
    "TargetProfileResource",
    "TargetSemanticInterpretation",
    "TargetStateEffect",
    "mcp_inventory_evidence_refs",
    "mcp_resource_id",
    "EXECUTION_TARGET_PROFILE_SCHEMA_VERSION",
    # semantic_conditions
    "AbsenceCondition",
    "ActionPresenceCondition",
    "ActionValueCondition",
    "ClosedSemanticModel",
    "DelayCondition",
    "DurationCondition",
    "OrderingCondition",
    "SemanticBindingPlaceholder",
    "SemanticBindingValueType",
    "SemanticCondition",
    "SemanticValue",
    "StateValueCondition",
    "WindowCondition",
    "contains_binding_placeholder",
    # scenario_spec
    "AttackerBDI",
    "DefenderBDI",
    "DefenderBelief",
    "DefenderDesire",
    "DefenderIntention",
    "ScenarioSpec",
    "ThreatSource",
    # scenario_envelope
    "ConsumerHints",
    "GherkinSpec",
    "ScenarioEnvelope",
    "SystemContext",
]
